

samples: "/home/ntpierce/2019-burgers-shrooms/mmetsp_info/all_mmetsp_elvers.csv"
pep_dir: "/home/ntpierce/2019-burgers-shrooms/mmetsp_info/mmetsp_pep"
samplelist: "mmetsp.txt"
out_dir: "mmetsp_pepsmash"
wrappers_dir: /home/ntpierce/2020-pep/wrappers
scaled:
  - 1
ksizes:
#  - 7
#  - 11
#  - 17
#  - 21
#  - 25
#  - 27
  - 31
#  - 33
#  - 35
#  - 39
#  - 41
encodings:
#  - protein
  - dayhoff
#  - hp
