

samples: "/home/ntpierce/2019-burgers-shrooms/mmetsp_info/all_mmetsp_elvers.csv"
pep_dir: "/home/ntpierce/2019-burgers-shrooms/mmetsp_info/mmetsp_pep"
samplelist: "mmetsp.txt"
out_dir: "mmetsp_pepsmash"
scaled: 2000
ksizes:
  - 7
  - 11
  - 17
encodings:
  - protein
  - dayhoff
  - hp
