

samples: "/home/ntpierce/2019-burgers-shrooms/mmetsp_info/all_mmetsp_elvers.csv"
pep_dir: "/home/ntpierce/2019-burgers-shrooms/mmetsp_info/mmetsp_pep"
out_dir: mmetsp_broccoli
samplelist: mmetsp_samplelist.txt
